SG_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  

  joint3_position_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  

  joint4_position_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  

  joint5_position_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
