SG_robot:
 state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
 robot_joint_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
   - shoulder_yaw_joint
   - shoulder_pitch_joint
   - elbow_pitch_joint
   - wrist_pitch_joint
   - wrist_roll_joint
  gazebo_ros_control/pid_gains:
   shoulder_yaw_joint:  
    - p: 10.0
    - i: 0.0
    - d: 0.0
   shoulder_pitch_joint:  
    - p: 10.0
    - i: 0.0
    - d: 0.0
   elbow_pitch_joint:  
    - p: 10.0
    - i: 0.0
    - d: 0.0
   wrist_pitch_joint:  
    - p: 10.0
    - i: 0.0
    - d: 0.0
   wrist_roll_joint:  
    - p: 10.0
    - i: 0.0
    - d: 0.0
   

     
