SG_robot:
  state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50
  shoulder_yaw_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_yaw_joint
    pid: {p: 2.0, i: 0.0, d: 100.0}
  shoulder_pitch_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_pitch_joint
    pid: {p: 2.0, i: 0.0, d: 100.0}
  elbow_pitch_joint_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_pitch_joint
    pid: {p: 2.0, i: 0.0, d: 100.0}
 
