SG_robot:
  state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50
  shoulder_yaw_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_yaw_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
  shoulder_pitch_joint_controller:
    type: effort_controllers/JointEffortController
    joint: shoulder_pitch_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
  elbow_pitch_joint_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_pitch_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
  wrist_pitch_joint_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_pitch_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
  wrist_roll_joint_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_roll_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
  gripper_right_joint_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_right_joint
    pid: {p: 2000.0, i: 0.01, d: 1.0}
     
