SG_robot:
  hardware_interface:
     loop_hz: 10 # hz
     joints:
       - shoulder_yaw_joint 
       - shoulder_pitch_joint
       - elbow_pitch_joint
       - wrist_pitch_joint
       - wrist_roll_joint
       - gripper_right_joint
      
