#SG_robot:
  joint_limits:

    shoulder_yaw_joint:
      has_position_limits: true
      min_position: 0.0
      max_position: 5.0
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    shoulder_pitch_joint:
      has_position_limits: true
      min_position: 0
      max_position: 3
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    elbow_pitch_joint:
      has_position_limits: true
      min_position: 0
      max_position: 3
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    wrist_pitch_joint:
      has_position_limits: true
      min_position: 0
      max_position: 3
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    wrist_roll_joint:
      has_position_limits: true
      min_position: 0
      max_position: 5
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    gripper_right_joint:
      has_position_limits: true
      min_position: 0
      max_position: 0.03
      has_velocity_limits: true
      max_velocity: 6.178465545
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    
