SG_robot:
  joint_offsets:
    shoulder_yaw_joint: 0.03
    shoulder_pitch_joint: 0.03
    elbow_pitch_joint: 0.03
    wrist_pitch_joint: 0.03
    wrist_roll_joint: 0.03   
    gripper_right_joint: 0.03                 

 
